# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: joystick.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='joystick.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ejoystick.proto\"\x1f\n\x0cJoystick_btn\x12\x0f\n\x07\x42uttons\x18\x01 \x03(\t\"d\n\rJoystick_Axis\x12&\n\x04\x61xis\x18\x01 \x03(\x0b\x32\x18.Joystick_Axis.AxisEntry\x1a+\n\tAxisEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')
)




_JOYSTICK_BTN = _descriptor.Descriptor(
  name='Joystick_btn',
  full_name='Joystick_btn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Buttons', full_name='Joystick_btn.Buttons', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=49,
)


_JOYSTICK_AXIS_AXISENTRY = _descriptor.Descriptor(
  name='AxisEntry',
  full_name='Joystick_Axis.AxisEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Joystick_Axis.AxisEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Joystick_Axis.AxisEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=151,
)

_JOYSTICK_AXIS = _descriptor.Descriptor(
  name='Joystick_Axis',
  full_name='Joystick_Axis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axis', full_name='Joystick_Axis.axis', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_JOYSTICK_AXIS_AXISENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=151,
)

_JOYSTICK_AXIS_AXISENTRY.containing_type = _JOYSTICK_AXIS
_JOYSTICK_AXIS.fields_by_name['axis'].message_type = _JOYSTICK_AXIS_AXISENTRY
DESCRIPTOR.message_types_by_name['Joystick_btn'] = _JOYSTICK_BTN
DESCRIPTOR.message_types_by_name['Joystick_Axis'] = _JOYSTICK_AXIS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Joystick_btn = _reflection.GeneratedProtocolMessageType('Joystick_btn', (_message.Message,), dict(
  DESCRIPTOR = _JOYSTICK_BTN,
  __module__ = 'joystick_pb2'
  # @@protoc_insertion_point(class_scope:Joystick_btn)
  ))
_sym_db.RegisterMessage(Joystick_btn)

Joystick_Axis = _reflection.GeneratedProtocolMessageType('Joystick_Axis', (_message.Message,), dict(

  AxisEntry = _reflection.GeneratedProtocolMessageType('AxisEntry', (_message.Message,), dict(
    DESCRIPTOR = _JOYSTICK_AXIS_AXISENTRY,
    __module__ = 'joystick_pb2'
    # @@protoc_insertion_point(class_scope:Joystick_Axis.AxisEntry)
    ))
  ,
  DESCRIPTOR = _JOYSTICK_AXIS,
  __module__ = 'joystick_pb2'
  # @@protoc_insertion_point(class_scope:Joystick_Axis)
  ))
_sym_db.RegisterMessage(Joystick_Axis)
_sym_db.RegisterMessage(Joystick_Axis.AxisEntry)


_JOYSTICK_AXIS_AXISENTRY._options = None
# @@protoc_insertion_point(module_scope)
