# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='eCAL.pb.play',
  syntax='proto3',
  serialized_options=_b('\200\001\001'),
  serialized_pb=_b('\n\rservice.proto\x12\x0c\x65\x43\x41L.pb.play\"t\n\rConfiguration\x12\x35\n\x05items\x18\x01 \x03(\x0b\x32&.eCAL.pb.play.Configuration.ItemsEntry\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x12\n\x10GetConfigRequest\"}\n\x11GetConfigResponse\x12+\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1b.eCAL.pb.play.Configuration\x12,\n\x06result\x18\x02 \x01(\x0e\x32\x1c.eCAL.pb.play.eServiceResult\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"?\n\x10SetConfigRequest\x12+\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1b.eCAL.pb.play.Configuration\"\x82\x03\n\x0e\x43ommandRequest\x12\x36\n\x07\x63ommand\x18\x01 \x01(\x0e\x32%.eCAL.pb.play.CommandRequest.eCommand\x12I\n\x0f\x63hannel_mapping\x18\x02 \x03(\x0b\x32\x30.eCAL.pb.play.CommandRequest.ChannelMappingEntry\x12\x1e\n\x16step_reference_channel\x18\x03 \x01(\t\x12\x15\n\rrel_time_secs\x18\x04 \x01(\x02\x1a\x35\n\x13\x43hannelMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x7f\n\x08\x65\x43ommand\x12\x08\n\x04none\x10\x00\x12\x0e\n\ninitialize\x10\x01\x12\x11\n\rde_initialize\x10\x02\x12\x0b\n\x07jump_to\x10\x03\x12\x08\n\x04play\x10\x04\x12\t\n\x05pause\x10\x05\x12\x08\n\x04step\x10\x06\x12\x10\n\x0cstep_channel\x10\x07\x12\x08\n\x04\x65xit\x10\x08\"G\n\x08Response\x12,\n\x06result\x18\x01 \x01(\x0e\x32\x1c.eCAL.pb.play.eServiceResult\x12\r\n\x05\x65rror\x18\x02 \x01(\t*3\n\x0e\x65ServiceResult\x12\x08\n\x04none\x10\x00\x12\x0b\n\x07success\x10\x01\x12\n\n\x06\x66\x61iled\x10\x02\x32\xe8\x01\n\x0f\x45\x63\x61lPlayService\x12L\n\tGetConfig\x12\x1e.eCAL.pb.play.GetConfigRequest\x1a\x1f.eCAL.pb.play.GetConfigResponse\x12\x43\n\tSetConfig\x12\x1e.eCAL.pb.play.SetConfigRequest\x1a\x16.eCAL.pb.play.Response\x12\x42\n\nSetCommand\x12\x1c.eCAL.pb.play.CommandRequest\x1a\x16.eCAL.pb.play.ResponseB\x03\x80\x01\x01\x62\x06proto3')
)

_ESERVICERESULT = _descriptor.EnumDescriptor(
  name='eServiceResult',
  full_name='eCAL.pb.play.eServiceResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='success', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='failed', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=823,
  serialized_end=874,
)
_sym_db.RegisterEnumDescriptor(_ESERVICERESULT)

eServiceResult = enum_type_wrapper.EnumTypeWrapper(_ESERVICERESULT)
none = 0
success = 1
failed = 2


_COMMANDREQUEST_ECOMMAND = _descriptor.EnumDescriptor(
  name='eCommand',
  full_name='eCAL.pb.play.CommandRequest.eCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='none', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='initialize', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='de_initialize', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='jump_to', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='play', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='pause', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='step', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='step_channel', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='exit', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=621,
  serialized_end=748,
)
_sym_db.RegisterEnumDescriptor(_COMMANDREQUEST_ECOMMAND)


_CONFIGURATION_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='eCAL.pb.play.Configuration.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='eCAL.pb.play.Configuration.ItemsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='eCAL.pb.play.Configuration.ItemsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=147,
)

_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='eCAL.pb.play.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='eCAL.pb.play.Configuration.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONFIGURATION_ITEMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=147,
)


_GETCONFIGREQUEST = _descriptor.Descriptor(
  name='GetConfigRequest',
  full_name='eCAL.pb.play.GetConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=167,
)


_GETCONFIGRESPONSE = _descriptor.Descriptor(
  name='GetConfigResponse',
  full_name='eCAL.pb.play.GetConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='eCAL.pb.play.GetConfigResponse.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='eCAL.pb.play.GetConfigResponse.result', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='eCAL.pb.play.GetConfigResponse.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=294,
)


_SETCONFIGREQUEST = _descriptor.Descriptor(
  name='SetConfigRequest',
  full_name='eCAL.pb.play.SetConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='eCAL.pb.play.SetConfigRequest.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=359,
)


_COMMANDREQUEST_CHANNELMAPPINGENTRY = _descriptor.Descriptor(
  name='ChannelMappingEntry',
  full_name='eCAL.pb.play.CommandRequest.ChannelMappingEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='eCAL.pb.play.CommandRequest.ChannelMappingEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='eCAL.pb.play.CommandRequest.ChannelMappingEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=619,
)

_COMMANDREQUEST = _descriptor.Descriptor(
  name='CommandRequest',
  full_name='eCAL.pb.play.CommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='eCAL.pb.play.CommandRequest.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_mapping', full_name='eCAL.pb.play.CommandRequest.channel_mapping', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step_reference_channel', full_name='eCAL.pb.play.CommandRequest.step_reference_channel', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rel_time_secs', full_name='eCAL.pb.play.CommandRequest.rel_time_secs', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COMMANDREQUEST_CHANNELMAPPINGENTRY, ],
  enum_types=[
    _COMMANDREQUEST_ECOMMAND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=748,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='eCAL.pb.play.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='eCAL.pb.play.Response.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='eCAL.pb.play.Response.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=750,
  serialized_end=821,
)

_CONFIGURATION_ITEMSENTRY.containing_type = _CONFIGURATION
_CONFIGURATION.fields_by_name['items'].message_type = _CONFIGURATION_ITEMSENTRY
_GETCONFIGRESPONSE.fields_by_name['config'].message_type = _CONFIGURATION
_GETCONFIGRESPONSE.fields_by_name['result'].enum_type = _ESERVICERESULT
_SETCONFIGREQUEST.fields_by_name['config'].message_type = _CONFIGURATION
_COMMANDREQUEST_CHANNELMAPPINGENTRY.containing_type = _COMMANDREQUEST
_COMMANDREQUEST.fields_by_name['command'].enum_type = _COMMANDREQUEST_ECOMMAND
_COMMANDREQUEST.fields_by_name['channel_mapping'].message_type = _COMMANDREQUEST_CHANNELMAPPINGENTRY
_COMMANDREQUEST_ECOMMAND.containing_type = _COMMANDREQUEST
_RESPONSE.fields_by_name['result'].enum_type = _ESERVICERESULT
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION
DESCRIPTOR.message_types_by_name['GetConfigRequest'] = _GETCONFIGREQUEST
DESCRIPTOR.message_types_by_name['GetConfigResponse'] = _GETCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['SetConfigRequest'] = _SETCONFIGREQUEST
DESCRIPTOR.message_types_by_name['CommandRequest'] = _COMMANDREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['eServiceResult'] = _ESERVICERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), dict(

  ItemsEntry = _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), dict(
    DESCRIPTOR = _CONFIGURATION_ITEMSENTRY,
    __module__ = 'service_pb2'
    # @@protoc_insertion_point(class_scope:eCAL.pb.play.Configuration.ItemsEntry)
    ))
  ,
  DESCRIPTOR = _CONFIGURATION,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.play.Configuration)
  ))
_sym_db.RegisterMessage(Configuration)
_sym_db.RegisterMessage(Configuration.ItemsEntry)

GetConfigRequest = _reflection.GeneratedProtocolMessageType('GetConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCONFIGREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.play.GetConfigRequest)
  ))
_sym_db.RegisterMessage(GetConfigRequest)

GetConfigResponse = _reflection.GeneratedProtocolMessageType('GetConfigResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETCONFIGRESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.play.GetConfigResponse)
  ))
_sym_db.RegisterMessage(GetConfigResponse)

SetConfigRequest = _reflection.GeneratedProtocolMessageType('SetConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETCONFIGREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.play.SetConfigRequest)
  ))
_sym_db.RegisterMessage(SetConfigRequest)

CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), dict(

  ChannelMappingEntry = _reflection.GeneratedProtocolMessageType('ChannelMappingEntry', (_message.Message,), dict(
    DESCRIPTOR = _COMMANDREQUEST_CHANNELMAPPINGENTRY,
    __module__ = 'service_pb2'
    # @@protoc_insertion_point(class_scope:eCAL.pb.play.CommandRequest.ChannelMappingEntry)
    ))
  ,
  DESCRIPTOR = _COMMANDREQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.play.CommandRequest)
  ))
_sym_db.RegisterMessage(CommandRequest)
_sym_db.RegisterMessage(CommandRequest.ChannelMappingEntry)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.play.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None
_CONFIGURATION_ITEMSENTRY._options = None
_COMMANDREQUEST_CHANNELMAPPINGENTRY._options = None

_ECALPLAYSERVICE = _descriptor.ServiceDescriptor(
  name='EcalPlayService',
  full_name='eCAL.pb.play.EcalPlayService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=877,
  serialized_end=1109,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetConfig',
    full_name='eCAL.pb.play.EcalPlayService.GetConfig',
    index=0,
    containing_service=None,
    input_type=_GETCONFIGREQUEST,
    output_type=_GETCONFIGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetConfig',
    full_name='eCAL.pb.play.EcalPlayService.SetConfig',
    index=1,
    containing_service=None,
    input_type=_SETCONFIGREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetCommand',
    full_name='eCAL.pb.play.EcalPlayService.SetCommand',
    index=2,
    containing_service=None,
    input_type=_COMMANDREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECALPLAYSERVICE)

DESCRIPTOR.services_by_name['EcalPlayService'] = _ECALPLAYSERVICE

# @@protoc_insertion_point(module_scope)
