# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import host_pb2 as host__pb2
import process_pb2 as process__pb2
import service_pb2 as service__pb2
import topic_pb2 as topic__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ecal.proto',
  package='eCAL.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\necal.proto\x12\x07\x65\x43\x41L.pb\x1a\nhost.proto\x1a\rprocess.proto\x1a\rservice.proto\x1a\x0btopic.proto\"_\n\x07\x43ontent\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x63lock\x18\x02 \x01(\x03\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x0c\n\x04size\x18\x06 \x01(\x05\x12\x0c\n\x04hash\x18\x07 \x01(\x03\"\xd2\x01\n\x06Sample\x12#\n\x08\x63md_type\x18\x01 \x01(\x0e\x32\x11.eCAL.pb.eCmdType\x12\x1b\n\x04host\x18\x02 \x01(\x0b\x32\r.eCAL.pb.Host\x12!\n\x07process\x18\x03 \x01(\x0b\x32\x10.eCAL.pb.Process\x12!\n\x07service\x18\x04 \x01(\x0b\x32\x10.eCAL.pb.Service\x12\x1d\n\x05topic\x18\x05 \x01(\x0b\x32\x0e.eCAL.pb.Topic\x12!\n\x07\x63ontent\x18\x06 \x01(\x0b\x32\x10.eCAL.pb.Content*\x85\x01\n\x08\x65\x43mdType\x12\x0c\n\x08\x62\x63t_none\x10\x00\x12\x12\n\x0e\x62\x63t_set_sample\x10\x01\x12\x15\n\x11\x62\x63t_reg_publisher\x10\x02\x12\x16\n\x12\x62\x63t_reg_subscriber\x10\x03\x12\x13\n\x0f\x62\x63t_reg_process\x10\x04\x12\x13\n\x0f\x62\x63t_reg_service\x10\x05\x62\x06proto3')
  ,
  dependencies=[host__pb2.DESCRIPTOR,process__pb2.DESCRIPTOR,service__pb2.DESCRIPTOR,topic__pb2.DESCRIPTOR,])

_ECMDTYPE = _descriptor.EnumDescriptor(
  name='eCmdType',
  full_name='eCAL.pb.eCmdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='bct_none', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bct_set_sample', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bct_reg_publisher', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bct_reg_subscriber', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bct_reg_process', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bct_reg_service', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=389,
  serialized_end=522,
)
_sym_db.RegisterEnumDescriptor(_ECMDTYPE)

eCmdType = enum_type_wrapper.EnumTypeWrapper(_ECMDTYPE)
bct_none = 0
bct_set_sample = 1
bct_reg_publisher = 2
bct_reg_subscriber = 3
bct_reg_process = 4
bct_reg_service = 5



_CONTENT = _descriptor.Descriptor(
  name='Content',
  full_name='eCAL.pb.Content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='eCAL.pb.Content.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clock', full_name='eCAL.pb.Content.clock', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='eCAL.pb.Content.time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='eCAL.pb.Content.payload', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='eCAL.pb.Content.size', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='eCAL.pb.Content.hash', index=5,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=173,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='eCAL.pb.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_type', full_name='eCAL.pb.Sample.cmd_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='eCAL.pb.Sample.host', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process', full_name='eCAL.pb.Sample.process', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='eCAL.pb.Sample.service', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='eCAL.pb.Sample.topic', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='eCAL.pb.Sample.content', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=386,
)

_SAMPLE.fields_by_name['cmd_type'].enum_type = _ECMDTYPE
_SAMPLE.fields_by_name['host'].message_type = host__pb2._HOST
_SAMPLE.fields_by_name['process'].message_type = process__pb2._PROCESS
_SAMPLE.fields_by_name['service'].message_type = service__pb2._SERVICE
_SAMPLE.fields_by_name['topic'].message_type = topic__pb2._TOPIC
_SAMPLE.fields_by_name['content'].message_type = _CONTENT
DESCRIPTOR.message_types_by_name['Content'] = _CONTENT
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.enum_types_by_name['eCmdType'] = _ECMDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), dict(
  DESCRIPTOR = _CONTENT,
  __module__ = 'ecal_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.Content)
  ))
_sym_db.RegisterMessage(Content)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLE,
  __module__ = 'ecal_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.Sample)
  ))
_sym_db.RegisterMessage(Sample)


# @@protoc_insertion_point(module_scope)
