# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitoring.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PyAgent.pb.host_pb2 as host__pb2
import PyAgent.pb.process_pb2 as process__pb2
import PyAgent.pb.service_pb2 as service__pb2
import PyAgent.pb.topic_pb2 as topic__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitoring.proto',
  package='eCAL.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10monitoring.proto\x12\x07\x65\x43\x41L.pb\x1a\nhost.proto\x1a\rprocess.proto\x1a\rservice.proto\x1a\x0btopic.proto\"t\n\nLogMessage\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\r\n\x05hname\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\r\n\x05pname\x18\x04 \x01(\t\x12\r\n\x05uname\x18\x05 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\"\x93\x01\n\nMonitoring\x12\x1c\n\x05hosts\x18\x01 \x03(\x0b\x32\r.eCAL.pb.Host\x12#\n\tprocesses\x18\x02 \x03(\x0b\x32\x10.eCAL.pb.Process\x12\"\n\x08services\x18\x03 \x03(\x0b\x32\x10.eCAL.pb.Service\x12\x1e\n\x06topics\x18\x04 \x03(\x0b\x32\x0e.eCAL.pb.Topic\",\n\x07Logging\x12!\n\x04logs\x18\x01 \x03(\x0b\x32\x13.eCAL.pb.LogMessageb\x06proto3')
  ,
  dependencies=[host__pb2.DESCRIPTOR,process__pb2.DESCRIPTOR,service__pb2.DESCRIPTOR,topic__pb2.DESCRIPTOR,])




_LOGMESSAGE = _descriptor.Descriptor(
  name='LogMessage',
  full_name='eCAL.pb.LogMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='eCAL.pb.LogMessage.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hname', full_name='eCAL.pb.LogMessage.hname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='eCAL.pb.LogMessage.pid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pname', full_name='eCAL.pb.LogMessage.pname', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uname', full_name='eCAL.pb.LogMessage.uname', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='eCAL.pb.LogMessage.level', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='eCAL.pb.LogMessage.content', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=200,
)


_MONITORING = _descriptor.Descriptor(
  name='Monitoring',
  full_name='eCAL.pb.Monitoring',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hosts', full_name='eCAL.pb.Monitoring.hosts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processes', full_name='eCAL.pb.Monitoring.processes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='services', full_name='eCAL.pb.Monitoring.services', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topics', full_name='eCAL.pb.Monitoring.topics', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=350,
)


_LOGGING = _descriptor.Descriptor(
  name='Logging',
  full_name='eCAL.pb.Logging',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logs', full_name='eCAL.pb.Logging.logs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=396,
)

_MONITORING.fields_by_name['hosts'].message_type = host__pb2._HOST
_MONITORING.fields_by_name['processes'].message_type = process__pb2._PROCESS
_MONITORING.fields_by_name['services'].message_type = service__pb2._SERVICE
_MONITORING.fields_by_name['topics'].message_type = topic__pb2._TOPIC
_LOGGING.fields_by_name['logs'].message_type = _LOGMESSAGE
DESCRIPTOR.message_types_by_name['LogMessage'] = _LOGMESSAGE
DESCRIPTOR.message_types_by_name['Monitoring'] = _MONITORING
DESCRIPTOR.message_types_by_name['Logging'] = _LOGGING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogMessage = _reflection.GeneratedProtocolMessageType('LogMessage', (_message.Message,), dict(
  DESCRIPTOR = _LOGMESSAGE,
  __module__ = 'monitoring_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.LogMessage)
  ))
_sym_db.RegisterMessage(LogMessage)

Monitoring = _reflection.GeneratedProtocolMessageType('Monitoring', (_message.Message,), dict(
  DESCRIPTOR = _MONITORING,
  __module__ = 'monitoring_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.Monitoring)
  ))
_sym_db.RegisterMessage(Monitoring)

Logging = _reflection.GeneratedProtocolMessageType('Logging', (_message.Message,), dict(
  DESCRIPTOR = _LOGGING,
  __module__ = 'monitoring_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.Logging)
  ))
_sym_db.RegisterMessage(Logging)


# @@protoc_insertion_point(module_scope)
