# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='topic.proto',
  package='eCAL.pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btopic.proto\x12\x07\x65\x43\x41L.pb\"]\n\x06TLayer\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.eCAL.pb.eTLayerType\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x11\n\tconfirmed\x18\x03 \x01(\x08\x12\x0b\n\x03par\x18\x04 \x01(\t\"\xb4\x02\n\x03QOS\x12\x38\n\x0breliability\x18\x01 \x01(\x0e\x32#.eCAL.pb.QOS.eQOSPolicy_Reliability\x12\x34\n\x07history\x18\x02 \x01(\x0e\x32#.eCAL.pb.QOS.eQOSPolicy_HistoryKind\x12\x15\n\rhistory_depth\x18\x03 \x01(\x05\"W\n\x16\x65QOSPolicy_Reliability\x12\x1f\n\x1b\x62\x65st_effort_reliability_qos\x10\x00\x12\x1c\n\x18reliable_reliability_qos\x10\x01\"M\n\x16\x65QOSPolicy_HistoryKind\x12\x19\n\x15keep_last_history_qos\x10\x00\x12\x18\n\x14keep_all_history_qos\x10\x01\"\xec\x02\n\x05Topic\x12\x0e\n\x06rclock\x18\x01 \x01(\x05\x12\x0b\n\x03hid\x18\x1a \x01(\x05\x12\r\n\x05hname\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\r\n\x05pname\x18\x04 \x01(\t\x12\r\n\x05uname\x18\x05 \x01(\t\x12\x0b\n\x03tid\x18\x06 \x01(\t\x12\r\n\x05tname\x18\x07 \x01(\t\x12\x11\n\tdirection\x18\x08 \x01(\t\x12\r\n\x05ttype\x18\t \x01(\t\x12\r\n\x05tdesc\x18\n \x01(\x0c\x12\x1a\n\x04tqos\x18\x0b \x01(\x0b\x32\x0c.eCAL.pb.QOS\x12\x1f\n\x06tlayer\x18\x0c \x03(\x0b\x32\x0f.eCAL.pb.TLayer\x12\r\n\x05tsize\x18\r \x01(\x05\x12\x17\n\x0f\x63onnections_loc\x18\x10 \x01(\x05\x12\x17\n\x0f\x63onnections_ext\x18\x11 \x01(\x05\x12\x15\n\rmessage_drops\x18\x12 \x01(\x05\x12\x0b\n\x03\x64id\x18\x13 \x01(\x03\x12\x0e\n\x06\x64\x63lock\x18\x14 \x01(\x03\x12\r\n\x05\x64\x66req\x18\x15 \x01(\x05*[\n\x0b\x65TLayerType\x12\x0b\n\x07tl_none\x10\x00\x12\x12\n\x0etl_ecal_udp_mc\x10\x01\x12\x0f\n\x0btl_ecal_shm\x10\x04\x12\r\n\ttl_inproc\x10*\x12\x0b\n\x06tl_all\x10\xff\x01\x62\x06proto3')
)

_ETLAYERTYPE = _descriptor.EnumDescriptor(
  name='eTLayerType',
  full_name='eCAL.pb.eTLayerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='tl_none', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='tl_ecal_udp_mc', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='tl_ecal_shm', index=2, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='tl_inproc', index=3, number=42,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='tl_all', index=4, number=255,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=797,
  serialized_end=888,
)
_sym_db.RegisterEnumDescriptor(_ETLAYERTYPE)

eTLayerType = enum_type_wrapper.EnumTypeWrapper(_ETLAYERTYPE)
tl_none = 0
tl_ecal_udp_mc = 1
tl_ecal_shm = 4
tl_inproc = 42
tl_all = 255


_QOS_EQOSPOLICY_RELIABILITY = _descriptor.EnumDescriptor(
  name='eQOSPolicy_Reliability',
  full_name='eCAL.pb.QOS.eQOSPolicy_Reliability',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='best_effort_reliability_qos', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='reliable_reliability_qos', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=262,
  serialized_end=349,
)
_sym_db.RegisterEnumDescriptor(_QOS_EQOSPOLICY_RELIABILITY)

_QOS_EQOSPOLICY_HISTORYKIND = _descriptor.EnumDescriptor(
  name='eQOSPolicy_HistoryKind',
  full_name='eCAL.pb.QOS.eQOSPolicy_HistoryKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='keep_last_history_qos', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='keep_all_history_qos', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=351,
  serialized_end=428,
)
_sym_db.RegisterEnumDescriptor(_QOS_EQOSPOLICY_HISTORYKIND)


_TLAYER = _descriptor.Descriptor(
  name='TLayer',
  full_name='eCAL.pb.TLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='eCAL.pb.TLayer.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='eCAL.pb.TLayer.version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confirmed', full_name='eCAL.pb.TLayer.confirmed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='par', full_name='eCAL.pb.TLayer.par', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=117,
)


_QOS = _descriptor.Descriptor(
  name='QOS',
  full_name='eCAL.pb.QOS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reliability', full_name='eCAL.pb.QOS.reliability', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='history', full_name='eCAL.pb.QOS.history', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='history_depth', full_name='eCAL.pb.QOS.history_depth', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QOS_EQOSPOLICY_RELIABILITY,
    _QOS_EQOSPOLICY_HISTORYKIND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=428,
)


_TOPIC = _descriptor.Descriptor(
  name='Topic',
  full_name='eCAL.pb.Topic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rclock', full_name='eCAL.pb.Topic.rclock', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hid', full_name='eCAL.pb.Topic.hid', index=1,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hname', full_name='eCAL.pb.Topic.hname', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='eCAL.pb.Topic.pid', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pname', full_name='eCAL.pb.Topic.pname', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uname', full_name='eCAL.pb.Topic.uname', index=5,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tid', full_name='eCAL.pb.Topic.tid', index=6,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tname', full_name='eCAL.pb.Topic.tname', index=7,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='eCAL.pb.Topic.direction', index=8,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ttype', full_name='eCAL.pb.Topic.ttype', index=9,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tdesc', full_name='eCAL.pb.Topic.tdesc', index=10,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tqos', full_name='eCAL.pb.Topic.tqos', index=11,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tlayer', full_name='eCAL.pb.Topic.tlayer', index=12,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tsize', full_name='eCAL.pb.Topic.tsize', index=13,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connections_loc', full_name='eCAL.pb.Topic.connections_loc', index=14,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connections_ext', full_name='eCAL.pb.Topic.connections_ext', index=15,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_drops', full_name='eCAL.pb.Topic.message_drops', index=16,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='did', full_name='eCAL.pb.Topic.did', index=17,
      number=19, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dclock', full_name='eCAL.pb.Topic.dclock', index=18,
      number=20, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dfreq', full_name='eCAL.pb.Topic.dfreq', index=19,
      number=21, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=795,
)

_TLAYER.fields_by_name['type'].enum_type = _ETLAYERTYPE
_QOS.fields_by_name['reliability'].enum_type = _QOS_EQOSPOLICY_RELIABILITY
_QOS.fields_by_name['history'].enum_type = _QOS_EQOSPOLICY_HISTORYKIND
_QOS_EQOSPOLICY_RELIABILITY.containing_type = _QOS
_QOS_EQOSPOLICY_HISTORYKIND.containing_type = _QOS
_TOPIC.fields_by_name['tqos'].message_type = _QOS
_TOPIC.fields_by_name['tlayer'].message_type = _TLAYER
DESCRIPTOR.message_types_by_name['TLayer'] = _TLAYER
DESCRIPTOR.message_types_by_name['QOS'] = _QOS
DESCRIPTOR.message_types_by_name['Topic'] = _TOPIC
DESCRIPTOR.enum_types_by_name['eTLayerType'] = _ETLAYERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TLayer = _reflection.GeneratedProtocolMessageType('TLayer', (_message.Message,), dict(
  DESCRIPTOR = _TLAYER,
  __module__ = 'topic_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.TLayer)
  ))
_sym_db.RegisterMessage(TLayer)

QOS = _reflection.GeneratedProtocolMessageType('QOS', (_message.Message,), dict(
  DESCRIPTOR = _QOS,
  __module__ = 'topic_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.QOS)
  ))
_sym_db.RegisterMessage(QOS)

Topic = _reflection.GeneratedProtocolMessageType('Topic', (_message.Message,), dict(
  DESCRIPTOR = _TOPIC,
  __module__ = 'topic_pb2'
  # @@protoc_insertion_point(class_scope:eCAL.pb.Topic)
  ))
_sym_db.RegisterMessage(Topic)


# @@protoc_insertion_point(module_scope)
